# Generated by Django 5.2.10 on 2026-02-02 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('degraded', 'Degraded Performance'), ('partial', 'Partial Outage'), ('major', 'Major Outage'), ('maintenance', 'Under Maintenance')], max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='status.service')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'unique_together': {('service', 'recorded_at')},
            },
        ),
    ]
