# Generated by Django 5.2.10 on 2026-02-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_statushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='statushistory',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_history', to='status.incident'),
        ),
    ]
