# Generated by Django 5.2.10 on 2026-02-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_statushistory_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
